'use strict';
const $=id=>document.getElementById(id);
let state=null,active=[],sound=false,audio=null,reactionTimer,music=null;
const rng=()=>Math.random();
const arrivals=[{name:'06:00 · The true believer',detail:'Place 4 · 4 hours waiting · already need a toilet',pos:4,bladder:32,minutes:240},{name:'08:30 · A reasonable person',detail:'Place 15 · 90 minutes waiting · a fighting chance',pos:15,bladder:15,minutes:90},{name:'09:55 · The opportunist',detail:'Place 26 · 5 minutes waiting · ethics are optional',pos:26,bladder:5,minutes:5}];
const events=[
{title:'Coffee. Your first mistake?',text:'The coffee cart arrives. It smells like warmth, hope, and a future bathroom emergency.',choices:[{name:'One coffee, please',detail:'€3 · bladder +22 · dignity +5',run:()=>{pay(3);state.bladder+=22;state.dignity+=5;return 'Warm hands. A rapidly cooling plan.'}},{name:'No thanks. I brought tap water.',detail:'Bladder +5 · save your money',run:()=>{state.bladder+=5;return 'The vendor nods. A fellow economist.'}},{name:'Distract everyone with free coffee',detail:'€9 · move forward 4 places · suspicion +18',cost:9,run:()=>{pay(9);state.pos-=4;state.susp+=18;state.dignity-=10;return 'Four people leave the queue. Several remember your face.'}}]},
{title:'Your bladder has a proposal.',text:'There is a toilet around the corner. The queue has no formal policy on human biology.',choices:[{name:'Ask your neighbour to hold your spot',detail:'Usually works · failure costs 6 places · empty bladder',run:()=>{state.bladder=0;if(rng()<.75){return '“I suppose.” The strongest friendship you have ever had.'}state.pos+=6;return 'Your neighbour has vanished. So has your place.'}},{name:'Hire a professional queuer',detail:'€8 · guaranteed spot · empty bladder',cost:8,run:()=>{pay(8);state.bladder=0;return 'Your substitute clocks in. The free bucket now has labour costs.'}},{name:'Hold it. This is bigger than me.',detail:'Bladder +18 · keep your place',run:()=>{state.bladder+=18;return 'Your commitment is admirable. Your posture is concerning.'}}]},
{title:'“Oh! There you are!”',text:'Someone waves near the front. Definitely not at you. But perhaps reality is negotiable.',choices:[{name:'Pretend they are your friend',detail:'65% chance: forward 6 · otherwise back 3 · suspicion +30',run:()=>{state.susp+=30;state.dignity-=18;if(rng()<.65){state.pos-=6;return '“Long time no see!” They stare into your soul.'}state.pos+=3;return '“Who are you?” The queue waits for an answer.'}},{name:'Stay in your rightful place',detail:'Suspicion −12 · dignity +10',run:()=>{state.susp-=12;state.dignity+=10;return 'You stare at the pavement. As tradition demands.'}},{name:'Offer someone €6 for their spot',detail:'€6 · forward 3 places · suspicion +5',cost:6,run:()=>{pay(6);state.pos-=3;state.susp+=5;return 'A legal transaction. A questionable investment.'}}]},
{title:'An expert in standing still.',text:'A professional queuer can handle the boring part. Their business card says “Your patience, outsourced.”',choices:[{name:'Hire them. Take a break.',detail:'€10 · bladder −30 · guaranteed 3 places forward',cost:10,run:()=>{pay(10);state.bladder-=30;state.pos-=3;return 'They negotiate a better place. You negotiate with your conscience.'}},{name:'Ask for free advice',detail:'Suspicion −8 · bladder +5',run:()=>{state.susp-=8;state.bladder+=5;return '“Stand here. Continue standing here.” Worth every cent.'}},{name:'Claim to be their supervisor',detail:'60% chance: forward 5 · otherwise back 2 · suspicion +25',run:()=>{state.susp+=25;state.dignity-=20;if(rng()<.6){state.pos-=5;return 'Your invented job comes with excellent queue benefits.'}state.pos+=2;return 'They ask for your employee number. You say “bucket”.'}}]},
{title:'The sausage queue incident.',text:'The line forks around a bench. One branch smells delicious. Neither branch has a sign.',choices:[{name:'Follow the people watching the stand',detail:'Forward 2 · bladder +6',run:()=>{state.pos-=2;state.bladder+=6;return 'Eyes on the buckets. These are your people.'}},{name:'Take the suspiciously short branch',detail:'50% chance: forward 5 · otherwise back 5',run:()=>{if(rng()<.5){state.pos-=5;return 'An inspired tactical manoeuvre. Nobody mentions it.'}state.pos+=5;return 'Congratulations. You are first in line for a €7 sausage.'}},{name:'Cut straight across the bench',detail:'Forward 6 · suspicion +32 · dignity −15',run:()=>{state.pos-=6;state.susp+=32;state.dignity-=15;return 'Six heads turn. One person removes their sunglasses.'}}]},
{title:'“There is a queue.”',text:'Someone has noticed your enthusiasm. The entire line falls silent. You can hear a distant gull judging you.',choices:[{name:'Apologise. Very quietly.',detail:'Back 2 places · suspicion −30 · dignity +8',run:()=>{state.pos+=2;state.susp-=30;state.dignity+=8;return '“Right.” Your case is closed. For now.'}},{name:'Buy peace with cinnamon buns',detail:'€5 · suspicion −25 · bladder +8',cost:5,run:()=>{pay(5);state.susp-=25;state.bladder+=8;return 'Diplomatic pastry. Finland remains at peace.'}},{name:'“Actually, I was here first.”',detail:'Forward 4 · suspicion +35 · dignity −20',run:()=>{state.pos-=4;state.susp+=35;state.dignity-=20;return 'A bold statement. The witnesses disagree.'}}]},
{title:'A rumour moves down the line.',text:'“There are fewer buckets than they promised.” Panic, expressed as slightly firmer standing, grips the crowd.',choices:[{name:'Stay calm. Trust the system.',detail:'Suspicion −10 · bladder +8',run:()=>{state.susp-=10;state.bladder+=8;return 'You trust the system. The system offers no comment.'}},{name:'Buy a better position',detail:'€7 · forward 5 places',cost:7,run:()=>{pay(7);state.pos-=5;return 'Someone decides €7 is worth more than a €2 bucket. Strange.'}},{name:'Announce a second bucket stand',detail:'70% chance: forward 7 · otherwise back 2 · suspicion +28',run:()=>{state.susp+=28;state.dignity-=22;if(rng()<.7){state.pos-=7;return 'A few people follow your completely fictional directions.'}state.pos+=2;return '“Where?” You point vaguely at Sweden.'}}]},
{title:'The doors finally open.',text:'Buckets start leaving the stand. Your bladder, your wallet, and your moral compass request a final meeting.',choices:[{name:'Proceed in an orderly fashion',detail:'Keep your place · let fate decide',run:()=> 'One small step for you. One enormous day for plastic.'},{name:'Pay for one final favour',detail:'€6 · forward 4 places · suspicion +8',cost:6,run:()=>{pay(6);state.pos-=4;state.susp+=8;return 'You complete your investment portfolio: one bucket.'}},{name:'Make a desperate dash',detail:'Forward 7 · suspicion +40 · dignity −30',run:()=>{state.pos-=7;state.susp+=40;state.dignity-=30;return 'You move. Every head turns. A cough sounds like a verdict.'}}]}
];
function pay(n){state.cash-=n;state.spent+=n}
function beep(type='move'){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=type==='bad'?120:type==='win'?660:330;g.gain.setValueAtTime(.08,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.22);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.23)}catch{}}
function art(root=document){root.querySelectorAll('[data-asset]').forEach(img=>{if(img.dataset.loaded)return;img.dataset.loaded='1';img.onload=()=>{img.style.display='block';const f=img.parentElement.querySelector('.fallback,.emoji');if(f)f.style.display='none'};img.onerror=()=>{img.style.display='none'};img.src='assets/'+img.dataset.asset})}
function queue(){const count=state?Math.min(8,Math.max(1,state.pos)):8;const visiblePlayer=state?Math.min(count-1,Math.max(0,state.pos-1)):5;const people=['🧍‍♂️','🧍‍♀️','🧥','👨‍🦳','👩‍🦰','🧍','👨‍🦱','👩‍🦳'];$('queue').innerHTML=Array.from({length:count},(_,i)=>{const player=i===visiblePlayer;return `<div class="person ${player?'player':''} ${player&&state?.bladder>=70?'urgent':''}"><img class="sprite art" data-asset="${player?'player-idle.png':'queuer-'+(i%4+1)+'.png'}" alt=""><span class="emoji">${player?'🧍':people[i]}</span><span class="tag">${player?'YOU':i===0?'NEXT':''}</span></div>`}).join('');art($('queue'))}
function hud(){if(!state){queue();art();return}state.pos=Math.max(1,state.pos);state.bladder=Math.max(0,Math.min(100,state.bladder));state.susp=Math.max(0,Math.min(100,state.susp));state.dignity=Math.max(0,Math.min(100,state.dignity));$('position').textContent='#'+state.pos;$('stock').textContent=state.stock;$('cash').textContent='€'+state.cash;$('bladder').value=state.bladder;$('bladderText').textContent=state.bladder+'%';$('suspicion').value=state.susp;$('suspicionText').textContent=state.susp>=75?'Last warning':state.susp>=45?'Collective stare':state.susp>=20?'A glance':'Invisible';$('round').textContent=`Decision ${Math.min(state.step+1,8)} / 8 · use 1 / 2 / 3`;$('clock').textContent=`SATURDAY · ${state.step>=7?'10:00':String(Math.floor((600-state.minutes*(1-state.step/8))/60)).padStart(2,'0')+':'+String(Math.floor((600-state.minutes*(1-state.step/8))%60)).padStart(2,'0')}`;$('sceneCaption').textContent=state.pos<=state.stock?'A bucket is within reach. Keep it together.':'More people than buckets. Time for a plan.';queue()}
function buttons(items){active=items;$('choices').innerHTML=items.map((c,i)=>`<button class="choice ${c.primary?'primary':''}" data-choice="${i}" ${c.cost>state?.cash?'disabled':''}><span class="key">${i+1}</span><span><strong>${c.name}</strong><small>${c.cost>state?.cash?'Not enough cash · '+c.detail:c.detail||''}</small></span></button>`).join('');$('choices').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>choose(i))}
function choose(i){const c=active[i];if(!c||c.cost>state?.cash)return;c.action()}
function startScreen(){state=null;clearTimeout(reactionTimer);$('reaction').classList.remove('show');$('position').textContent='—';$('stock').textContent='18';$('cash').textContent='€30';$('bladder').value=0;$('bladderText').textContent='0%';$('suspicion').value=0;$('suspicionText').textContent='Invisible';$('clock').textContent='SATURDAY · 06:00';$('round').textContent='Choose your arrival · 1 / 2 / 3 to play';$('sceneCaption').textContent='Some things in life are free. This will cost you.';$('panel').innerHTML='<div><div class="eyebrow">18 BUCKETS. ONE VERY LONG QUEUE.</div><h1>How early is too early?</h1><p>The discount shop opens at 10:00. The first 18 customers get a free bucket. You have €30 and a concerning amount of commitment.</p><p>Pick your arrival. Survive eight decisions. Keep your bladder below 100 and suspicion below 100.</p></div><div id="choices" class="choices"></div>';buttons(arrivals.map((a,i)=>({...a,primary:i===1,action:()=>start(i)})));hud()}
function start(i){state={...arrivals[i],cash:30,spent:0,susp:0,dignity:100,stock:18,step:0,phase:'event'};beep();hud();showEvent()}
function showEvent(){state.phase='event';const e=events[state.step];$('panel').innerHTML=`<div><div class="eyebrow">QUEUE INCIDENT ${state.step+1} / 8</div><h2>${e.title}</h2><p>${e.text}</p><p>Getting a bucket requires your place to be within the remaining supply when the doors open.</p></div><div id="choices" class="choices"></div>`;buttons(e.choices.map(c=>({...c,action:()=>resolve(c)})))}
function resolve(c){if(state.phase!=='event')return;const before=state.susp;const message=c.run();state.phase='outcome';const arrivalRate=state.minutes>=240?3:state.minutes>=90?2:1;state.bladder+=arrivalRate;state.pos=Math.max(1,state.pos);hud();beep(state.susp>before?'bad':'move');if(state.susp>before){$('reaction').textContent=state.susp>=100?'“Out. Now.”':state.susp>=75?'“This is your last warning.”':state.susp>=45?'“There is a queue.”':'* a disapproving cough *';$('reaction').classList.add('show');document.querySelectorAll('.person:not(.player)').forEach((p,i)=>setTimeout(()=>p.classList.add('turn'),i*90));clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>$('reaction').classList.remove('show'),2400)}
if(state.susp>=100){finish('expelled',message);return}if(state.bladder>=100){finish('bathroom',message);return}
$('panel').innerHTML=`<div><div class="eyebrow">${state.step===7?'THE MOMENT OF TRUTH':'THE QUEUE REMEMBERS'}</div><h2>${state.step===7?'Your turn is coming.':'And so you wait.'}</h2><p>${message}</p><p>Your place: <strong>#${state.pos}</strong> · ${state.stock} buckets remain.</p></div><div id="choices" class="choices"></div>`;buttons([{name:state.step===7?'Approach the bucket stand':'Keep waiting',detail:state.step===7?'Discover the true cost of free':'Continue to the next incident',primary:true,action:()=>{if(state.step===7){finish(state.pos<=state.stock?'win':'soldout');return}state.step++;if(state.step===7){const loss=2+Math.floor(rng()*3);state.stock-=loss}hud();showEvent()}}])}
function finish(kind,extra=''){state.phase='end';const win=kind==='win';const titles={win:'The bucket is yours.',soldout:'The last bucket just left.',expelled:'You have been un-queued.',bathroom:'Nature wins. You lose.'};const lines={win:'Two euros of plastic. A lifetime of stories. You lift it proudly. Everyone pretends not to care.',soldout:'The attendant offers you a brochure. It does not hold water. You stare at it anyway.',expelled:'The queue closes the gap with terrifying efficiency. Your name will live on in local WhatsApp groups.',bathroom:'You abandon the queue for an urgent appointment. Some victories cannot be postponed.'};$('round').textContent='RUN COMPLETE';$('clock').textContent='SATURDAY · 10:00';$('panel').innerHTML=`<div><div class="eyebrow">${win?'FREE BUCKET ACQUIRED':'NO BUCKET TODAY'}</div><h2>${titles[kind]}</h2><p>${lines[kind]}</p>${extra?'<p>'+extra+'</p>':''}<div id="choices" class="choices result-actions"></div></div><div class="receipt"><h3>HALPA HALLI · YOUR RECEIPT</h3><div><span>Plastic bucket</span><span>${win?'€0.00':'NOT ACQUIRED'}</span></div><div><span>Queue-related expenses</span><span>€${state.spent}.00</span></div><div><span>Time committed</span><span>${state.minutes} min</span></div><div><span>Dignity remaining</span><span>${state.dignity}%</span></div><div><span>Retail bucket value</span><span>€2.00</span></div><div class="total"><span>PRICE OF FREE</span><span>€${state.spent} + your morning</span></div></div>`;buttons([{name:'Queue again',detail:'Another morning. Another questionable decision.',primary:true,action:startScreen}]);beep(win?'win':'bad')}
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'Sound on':'Sound off';$('sound').setAttribute('aria-pressed',String(sound));if(sound){try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();music??=new QueueMusic(audio);music.start();beep()}catch{sound=false;$('sound').textContent='Sound unavailable';$('sound').setAttribute('aria-pressed','false')}}else{music?.stop()}};document.addEventListener('keydown',e=>{if(e.altKey||e.metaKey||e.ctrlKey||e.repeat)return;const i=Number(e.key)-1;if(i>=0&&i<3){e.preventDefault();choose(i)}});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();const tool=(name,description,inputSchema,execute,readOnlyHint=false)=>{try{Promise.resolve(document.modelContext.registerTool({name,description,inputSchema,execute,annotations:{readOnlyHint}},{signal:lifecycle.signal})).catch(()=>{})}catch{}};const read=()=>state?{position:state.pos,buckets:state.stock,cash:state.cash,bladder:state.bladder,suspicion:state.susp,decision:state.step+1,phase:state.phase}: {phase:'arrival'};tool('read_queue_game','Read the current queue game state.',{type:'object',properties:{},additionalProperties:false},read,true);tool('choose_queue_action','Choose a currently visible option (1 to 3), including arrival and replay.',{type:'object',properties:{option:{type:'integer',minimum:1,maximum:3}},required:['option'],additionalProperties:false},input=>{if(!input||!Number.isInteger(input.option)||input.option<1||input.option>active.length||active[input.option-1].cost>state?.cash)throw new Error('Unavailable option');choose(input.option-1);return read()});window.addEventListener('pagehide',()=>lifecycle.abort())}
startScreen();
